export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
export const AUTHERROR = "AUTHERROR";

export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEY_BY_ID = "FETCH_SURVEY_BY_ID";
export const UPDATE_SURVEY_NAME = "UPDATE_SURVEY_NAME";
export const ADD_SURVEY_QUESTIONS = "ADD_SURVEY_QUESTIONS";
export const UPDATE_SURVEY_FLAG = "UPDATE_SURVEY_FLAG";
export const UPDATE_ALL_SURVEY_FLAG = "UPDATE_ALL_SURVEY_FLAG";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const SAVE_PREVIEW= "SAVE_PREVIEW";
export const FETCH_SUBMIT_SURVEY = "FETCH_SUBMIT_SURVEY";
export const FETCH_SURVEY_RESULTS = "FETCH_SURVEY_RESULTS";
export const SUBMIT_SURVEY = "SUBMIT_SURVEY";

export const CLEAR_DATA = "CLEAR_DATA";
